version: '3.3'

networks:
  cache:
    internal: true
  api:
#    internal: true
#  proxy:

volumes:
  app-logs:

services:
  redis_container:
    image: redis
    container_name: redis_container
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - cache

  app-urlshortner-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-urlshortner-api
    container_name: app-urlshortner-api
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - app-logs:/var/log/app
    networks:
      - api
      - cache
#      - proxy
    depends_on:
      - redis_container
#    healthcheck:
#      test: "curl -sS http://localhost:8080/actuator/health"
#      interval: 1s
#      timeout: 30s
#      retries: 60
