urlshortner.urlbase: http://localhost:8080/u/
urlshortner.error404: http://localhost:8080/404

server:
  port: 8080

spring:
  main:
    banner-mode: off

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://urlshortner-mysql:3306/urlshortner?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: urlshortner
    password: QwErTy
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: urlshortner-redis
      port: 6379
      repositories:
        enabled: false

  cache:
    type: redis

logging:
  file:
    max-size: 50mb
    max-history: 10
    path: /var/log/app
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.andsantos.urlshortner: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 400ms
    tags:
      application: urlshortner
  endpoints:
    web:
      exposure:
        include: "*"
