urlshortner.urlbase: http://localhost:8080/

server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.andsantos.urlshortner: INFO
        