urlshortner.urlbase: http://localhost:8080/

server:
  port: 8080

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: urlshortner

logging:
  level:
    ROOT: INFO
    org.mongodb: INFO
    com.andsantos.urlshortner: INFO
        