urlshortner.urlbase: http://localhost:8080/

server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/urlshortner;DB_CLOSE_DELAY=-1
    username: urlshortner
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.andsantos.urlshortner: INFO

management:
  server:
    port: 9000
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 400ms
    tags:
      application: urlshortner
  endpoints:
    web:
      exposure:
        include: "*"