urlshortner.urlbase: http://localhost:8080/u/
urlshortner.error404: http://localhost:8080/404

server:
  port: 8080

spring:
  main:
    banner-mode: off

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/urlshortner;DB_CLOSE_DELAY=-1
    username: urlshortner
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: urlshortner-redis
      port: 6379
      repositories:
        enabled: false

  cache:
    type: redis

#  redis:
#    host: 127.0.0.1
#    port: 16379

logging:
  file:
    max-size: 50mb
    max-history: 10
    path: /var/log/app
  level:
    ROOT: DEBUG
    org.hibernate.SQL: INFO
    com.andsantos.urlshortner: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 400ms
    tags:
      application: urlshortner
  endpoints:
    web:
      exposure:
        include: "*"
