global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: app-urlshortner-api
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - urlshortner-api:8080